image: maven:3.8-amazoncorretto-17

cache:
  paths:
    - .m2/repository
    - node_modules/

stages:          # List of stages for jobs, and their order of execution
  - audit
  - build
  #- test       ##uncomment
  - style-check

frontend:       # This job runs in the build stage, which runs first.
  image: node
  stage: build
  script:
    - npm config set proxy null
    - npm config set https-proxy null
    - npm config set registry http://registry.npmjs.org/
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
        - build/*

backend:
  stage: build
  script:
    - cd backend
    - mvn clean install
  artifacts:
    paths:
      - target/

#backend-test:
#  stage: test
#  script: 
#    - cd backend
#    - mvn test

#frontend-test:
#  image: node
#  stage: test
#  script: 
#    - npm config set proxy null
#    - npm config set https-proxy null
#    - npm config set registry http://registry.npmjs.org/
#    - cd frontend
#    - npm install
#    - npm run test

frontend-audit:
  image: node
  stage: audit
  script: 
    - npm config set proxy null
    - npm config set https-proxy null
    - npm config set registry http://registry.npmjs.org/
    - cd frontend
    - npm install
    - npm audit


style-check:
   stage: style-check
   script:
     - cd Frontend/frontend
     - npm install --save-dev eslint-config-react-app eslint@^8.0.0 eslint-config-prettier eslint-plugin-prettier
     - node_modules/eslint/bin/eslint.js .


