image: maven:3.8-amazoncorretto-17

cache:
  paths:
    - m2/repository

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - style-check

frontend:       # This job runs in the build stage, which runs first.
  image: node
  stage: build
  script:
    - npm config set proxy null
    - npm config set https-proxy null
    - npm config set registry http://registry.npmjs.org/
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
        - build/*

backend:
  stage: build
  script:
    - cd backend
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

backend-test:
  stage: test
  script: 
    - cd backend
    - mvn test
  artifacts:
    paths:
      - target/surefire-reports/*

style-check:
    stage: style-check
    script:
       - echo "Check styling"


