image: node

stages:          # List of stages for jobs, and their order of execution
  - build
  - style-check

frontend:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cd frontend
    - npm install

backend:
  stage: build
  script:
    - cd backend
    - chmod +x mvnw
    - ./mvnw clean install

style-check:
    stage: style-check
    script:
       - echo "Check styling"


