image: node:16

variables:
  no_proxy: registry.npmjs.org,.inso-w.com
  NO_PROXY: '$no_proxy'
  npm_config_cache: '${CI_PROJECT_DIR}/.npm'
  CONTAINER_REGISTRY: https://index.docker.io/v1/
  CI_REGISTRY_IMAGE: "waecm"

.cache: &node_cache
    key: 
      files: 
        - package.json
    paths:
      - frontend/.npm
      - frontend/node_modules

stages:
  - audit
  - build
  - test
  - style-check
  - deploy

npm:install:
  stage: .pre
  cache:
    <<: *node_cache
    policy: push
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline

#npm:audit:
#  stage: audit
#  needs: 
#    - job: npm:install
#  cache:
#    <<: *node_cache
#    policy: pull
#  script:
#    - cd frontend
#    - npm audit

frontend-build: 
  stage: build
  needs: 
    - job: npm:install
  cache:
    <<: *node_cache
    policy: pull
  script:
    - cd frontend
    - npm run build
  artifacts:
    paths:
      - frontend/dist

#backend:
#  image: maven:3.8-amazoncorretto-17
#  stage: build
#  script:
#    - cd backend
#    - mvn clean install
#  artifacts:
#    paths:
#      - target/

#frontend-test:
#  image: node
#  stage: test
#  needs: 
#    - job: frontend-build
#  script: 
#    - cd frontend
#    - npm install vitest
#    - npm run test

#frontend-style-check:
#   stage: style-check
#   script:
#     - cd frontend
#     - npm install --save-dev eslint-config-react-app eslint@^8.0.0
#     - node_modules/eslint/bin/eslint.js "src/**/*.{js,jsx}"

kaniko:frontend-docker-deploy:
  stage: deploy
  needs: 
    - job: frontend-build
  image:
    #name: gcr.io/kaniko-project/executor:debug
    #name: mgit/base:kaniko-executor-debug-stable
    #name: gcr.io/kaniko-project/executor:v1.6.0
    name: gcr.io/kaniko-project/executor:v1.6.0-debug
    entrypoint: [""]
  script:
    - cd frontend
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CONTAINER_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${DOCKER_HUB_USER}" "${DOCKER_HUB_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - echo ${CI_PROJECT_DIR}
    - >-
      /kaniko/executor
      --context ${CI_PROJECT_DIR}/frontend
      --dockerfile ${CI_PROJECT_DIR}/frontend/Dockerfile
      --destination ${CONTAINER_REGISTRY}${DOCKER_HUB_USER}/${CI_REGISTRY_IMAGE}:test


