image: maven:3.8-amazoncorretto-17

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - style-check
  - package

frontend:       # This job runs in the build stage, which runs first.
  image: node
  stage: build
  script:
    - npm config set proxy null
    - npm config set https-proxy null
    - npm config set registry http://registry.npmjs.org/
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
        - build/*

backend:
  stage: build
  script:
    - cd backend
    - mvn clean compile

backend-test:
  stage: test
  script: 
    - cd backend
    - mvn test
  artifacts:
    paths:
      - target/surefire-reports/*

backend-package:
    stage: package
    script:
      - cd backend
      - mvn install
    artifacts:
      paths:
        - target/*.jar

style-check:
    stage: style-check
    script:
       - echo "Check styling"


