image: node

stages:          # List of stages for jobs, and their order of execution
  - build
  - style-check

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cd frontend
    - npm install
    - cd ../backend
    - mvn clean install

style-check:
    stage: style-check
    script:
       - echo "Check styling"


