image: maven:3.8-amazoncorretto-17

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - style-check
  - package

frontend:       # This job runs in the build stage, which runs first.
  image: node
  stage: build
  script:
    - cd frontend
    - npm install

backend:
  stage: build
  script:
    - cd backend
    - mvn clean compile

backend-test:
  stage: test
  script: 
    - mvn test
  artifacts:
      paths:
          - target/surefire-reports/*

backend-package:
    stage: package
    script:
        - mvn package
    artifacts:
        paths:
            - target/*.jar

style-check:
    stage: style-check
    script:
       - echo "Check styling"


