# docker compose uebung 2
version: '3.9'

services:
    database:
        image: 'mongo:5.0'
        container_name: 'waecm-2022-group-08-bsp-2-mongoDb'
        ports:
            -   '27018:27017'
            
    frontend:
        image: diason/waecm:frontendLatest
        ports:
            - "4444:80"
        container_name: waecm-2022-group-08-bsp-3-frontend
    
    backend:
        image: diason/waecm:backendLatest
        ports:
            - "8080:8080"
        container_name: waecm-2022-group-08-bsp-3-backend
        environment:
            SPRING_APPLICATION_NAME: waecm-2022-group-08-bsp-2-backend
            SPRING_SLEUTH_ENABLED: "true"
