server:
  port: 8080

spring:
  data:
    mongodb:
      #user: waecm
      #password: waecm
      uri: mongodb://localhost:27018
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://waecm-sso.inso.tuwien.ac.at/realms/waecm
          jwk-set-uri: https://waecm-sso.inso.tuwien.ac.at/realms/waecm/protocol/openid-connect/certs
